/*

 CURSOR.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 20 to 23

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __cursor_h_INCLUDE
#define __cursor_h_INCLUDE

/* Bank of tiles. */
#define cursorBank 0

/* Super Gameboy palette 0 */
#define cursorSGBPal0c0 6076
#define cursorSGBPal0c1 8935
#define cursorSGBPal0c2 6596
#define cursorSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define cursorSGBPal1c0 6076
#define cursorSGBPal1c1 8935
#define cursorSGBPal1c2 6596
#define cursorSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define cursorSGBPal2c0 6076
#define cursorSGBPal2c1 8935
#define cursorSGBPal2c2 6596
#define cursorSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define cursorSGBPal3c0 6076
#define cursorSGBPal3c1 8935
#define cursorSGBPal3c2 6596
#define cursorSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define cursorCGBPal0c0 32767
#define cursorCGBPal0c1 22197
#define cursorCGBPal0c2 10570
#define cursorCGBPal0c3 0

/* Gameboy Color palette 1 */
#define cursorCGBPal1c0 9247
#define cursorCGBPal1c1 5135
#define cursorCGBPal1c2 5055
#define cursorCGBPal1c3 2511

/* Gameboy Color palette 2 */
#define cursorCGBPal2c0 7040
#define cursorCGBPal2c1 3520
#define cursorCGBPal2c2 32421
#define cursorCGBPal2c3 15682

/* Gameboy Color palette 3 */
#define cursorCGBPal3c0 671
#define cursorCGBPal3c1 335
#define cursorCGBPal3c2 20766
#define cursorCGBPal3c3 10383

/* Gameboy Color palette 4 */
#define cursorCGBPal4c0 6076
#define cursorCGBPal4c1 8935
#define cursorCGBPal4c2 6596
#define cursorCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define cursorCGBPal5c0 6076
#define cursorCGBPal5c1 8935
#define cursorCGBPal5c2 6596
#define cursorCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define cursorCGBPal6c0 6076
#define cursorCGBPal6c1 8935
#define cursorCGBPal6c2 6596
#define cursorCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define cursorCGBPal7c0 6076
#define cursorCGBPal7c1 8935
#define cursorCGBPal7c2 6596
#define cursorCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char cursor_gfx[];

#endif

/* End of CURSOR.H */
