/*

 EXPORT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 17

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Export_h_INCLUDE
#define __Export_h_INCLUDE

/* Bank of tiles. */
#define gametilesBank 0

/* Super Gameboy palette 0 */
#define gametilesSGBPal0c0 6076
#define gametilesSGBPal0c1 8935
#define gametilesSGBPal0c2 6596
#define gametilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define gametilesSGBPal1c0 6076
#define gametilesSGBPal1c1 8935
#define gametilesSGBPal1c2 6596
#define gametilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define gametilesSGBPal2c0 6076
#define gametilesSGBPal2c1 8935
#define gametilesSGBPal2c2 6596
#define gametilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define gametilesSGBPal3c0 6076
#define gametilesSGBPal3c1 8935
#define gametilesSGBPal3c2 6596
#define gametilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define gametilesCGBPal0c0 32767
#define gametilesCGBPal0c1 22197
#define gametilesCGBPal0c2 10570
#define gametilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define gametilesCGBPal1c0 9247
#define gametilesCGBPal1c1 5135
#define gametilesCGBPal1c2 5055
#define gametilesCGBPal1c3 2511

/* Gameboy Color palette 2 */
#define gametilesCGBPal2c0 7040
#define gametilesCGBPal2c1 3520
#define gametilesCGBPal2c2 32421
#define gametilesCGBPal2c3 15682

/* Gameboy Color palette 3 */
#define gametilesCGBPal3c0 671
#define gametilesCGBPal3c1 335
#define gametilesCGBPal3c2 20766
#define gametilesCGBPal3c3 10383

/* Gameboy Color palette 4 */
#define gametilesCGBPal4c0 6076
#define gametilesCGBPal4c1 8935
#define gametilesCGBPal4c2 6596
#define gametilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define gametilesCGBPal5c0 6076
#define gametilesCGBPal5c1 8935
#define gametilesCGBPal5c2 6596
#define gametilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define gametilesCGBPal6c0 6076
#define gametilesCGBPal6c1 8935
#define gametilesCGBPal6c2 6596
#define gametilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define gametilesCGBPal7c0 6076
#define gametilesCGBPal7c1 8935
#define gametilesCGBPal7c2 6596
#define gametilesCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char gametiles[];

#endif

/* End of EXPORT.H */
