/*

 PLAY_BACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : gametiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __play_background_h_INCLUDE
#define __play_background_h_INCLUDE

#define play_backgroundWidth 20
#define play_backgroundHeight 18
#define play_backgroundBank 0

#define play_background play_backgroundPLN0
extern const unsigned char play_backgroundPLN0[];
extern const unsigned char play_backgroundPLN1[];

#endif

/* End of PLAY_BACKGROUND.H */
